# Generated by Django 5.1.2 on 2024-10-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='years',
            field=models.TextField(max_length=4, null=True),
        ),
    ]
